// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("WebApplication1.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId")
                        .HasName("Comment_PK");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Content = "Great post!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1228),
                            PostId = 1,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 2,
                            Content = "Thanks for the tips!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1231),
                            PostId = 1,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 3,
                            Content = "I love budget travel!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1233),
                            PostId = 2,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 4,
                            Content = "Awesome information.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1234),
                            PostId = 2,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 5,
                            Content = "These recipes look delicious! Can't wait to try them.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1236),
                            PostId = 3,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 6,
                            Content = "I'm a fan of quick and easy recipes. Thanks for sharing!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1237),
                            PostId = 3,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 7,
                            Content = "Time management is crucial. I'll definitely apply these tips.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1239),
                            PostId = 4,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 8,
                            Content = "I struggle with time management. Your tips are helpful!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1241),
                            PostId = 4,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 9,
                            Content = "I never thought of DIY home decor. Excited to give it a try!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1242),
                            PostId = 5,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 10,
                            Content = "DIY home decor is a great way to personalize your space.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1244),
                            PostId = 5,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 11,
                            Content = "Mindfulness has changed my life. Can't wait to read more.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1246),
                            PostId = 6,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 12,
                            Content = "Mindfulness meditation has so many benefits. Thanks for sharing.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1247),
                            PostId = 6,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 13,
                            Content = "Home workouts are my go-to. Any specific exercises you recommend?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1249),
                            PostId = 7,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 14,
                            Content = "Budget-friendly fitness is the way to go! Great post.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1250),
                            PostId = 7,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 15,
                            Content = "Financial planning is something everyone should focus on. Thanks for the advice.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1252),
                            PostId = 8,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 16,
                            Content = "These financial planning tips are practical and helpful.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1254),
                            PostId = 8,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 17,
                            Content = "I've always wanted to try photography. Any camera recommendations?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1255),
                            PostId = 9,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 18,
                            Content = "Photography is a great hobby. Start with your smartphone camera!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1257),
                            PostId = 9,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 19,
                            Content = "Communication skills are essential. Can you recommend any books?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1259),
                            PostId = 10,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 20,
                            Content = "I'm working on my communication skills. These tips are valuable.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1260),
                            PostId = 10,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 21,
                            Content = "Gardening is a therapeutic hobby. Any plant suggestions for beginners?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1262),
                            PostId = 11,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 22,
                            Content = "I started gardening recently. Tomatoes and herbs are great for beginners!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1263),
                            PostId = 11,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 23,
                            Content = "Excited to explore the latest tech gadgets. Any personal recommendations?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1265),
                            PostId = 12,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 24,
                            Content = "Tech gadgets are always evolving. Stay updated and enjoy exploring!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1267),
                            PostId = 12,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 25,
                            Content = "Effective study habits are a game-changer. How do you handle distractions?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1268),
                            PostId = 13,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 26,
                            Content = "Creating a dedicated study space helps minimize distractions. Give it a try!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1270),
                            PostId = 13,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 27,
                            Content = "Public speaking terrifies me. Any tips for overcoming stage fright?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1271),
                            PostId = 14,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 28,
                            Content = "Practice is key! Start small, and gradually build your confidence on stage.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1273),
                            PostId = 14,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 29,
                            Content = "Minimalist living has changed my perspective. How did you start your journey?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1275),
                            PostId = 15,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 30,
                            Content = "I began by decluttering one room at a time. It's a gradual process, but so rewarding.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1276),
                            PostId = 15,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 31,
                            Content = "Healthy snacks are a lifesaver! Any favorite recipes you'd like to share?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1278),
                            PostId = 16,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 32,
                            Content = "Try mixing Greek yogurt with fruits for a delicious and healthy snack!",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1280),
                            PostId = 16,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 33,
                            Content = "Learning a new language sounds fascinating. How do you stay motivated?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1281),
                            PostId = 17,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 34,
                            Content = "I set small goals and celebrate achievements. It keeps me motivated to learn more.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1283),
                            PostId = 17,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 35,
                            Content = "Budget-friendly fitness gear is a must. Any specific brands you recommend?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1285),
                            PostId = 18,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 36,
                            Content = "Look for sales and discounts. Many reputable brands offer affordable options.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1286),
                            PostId = 18,
                            UserId = 4
                        },
                        new
                        {
                            CommentId = 37,
                            Content = "Productivity apps make a huge difference. Which ones are your favorites?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1288),
                            PostId = 19,
                            UserId = 1
                        },
                        new
                        {
                            CommentId = 38,
                            Content = "I swear by task management apps. They keep me organized and focused.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1290),
                            PostId = 19,
                            UserId = 2
                        },
                        new
                        {
                            CommentId = 39,
                            Content = "Nature photography is breathtaking. Any favorite locations for capturing nature shots?",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1291),
                            PostId = 20,
                            UserId = 3
                        },
                        new
                        {
                            CommentId = 40,
                            Content = "Visit parks, nature reserves, and scenic landscapes for stunning photography opportunities.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1293),
                            PostId = 20,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE('now')");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId")
                        .HasName("Post_PK");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Here are some tips for a healthy lifestyle...",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1061),
                            State = 0,
                            Title = "Healthy Lifestyle Tips",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Explore the world without breaking the bank...",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1119),
                            State = 0,
                            Title = "Traveling on a Budget",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Discover delicious recipes that are both quick and easy to prepare.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1122),
                            State = 0,
                            Title = "Quick and Easy Recipes",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Master the art of time management with these practical tips and techniques.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1123),
                            State = 0,
                            Title = "Effective Time Management",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Transform your living space with these creative and budget-friendly DIY home decor ideas.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1125),
                            State = 0,
                            Title = "DIY Home Decor Ideas",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Explore the benefits of mindfulness meditation and learn how to incorporate it into your daily routine.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1127),
                            State = 0,
                            Title = "Mindfulness Meditation Guide",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 7,
                            Content = "Start your fitness journey with a beginner-friendly workout routine that you can do at home.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1129),
                            State = 0,
                            Title = "Fitness Workout for Beginners",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 8,
                            Content = "Learn the basics of financial planning to secure your future and achieve your financial goals.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1130),
                            State = 0,
                            Title = "Financial Planning 101",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Capture stunning photos with these essential photography tips designed for amateur photographers.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1132),
                            State = 0,
                            Title = "Photography Tips for Amateurs",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Enhance your communication skills with practical strategies to express yourself more clearly and confidently.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1134),
                            State = 0,
                            Title = "Effective Communication Skills",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 11,
                            Content = "Start your own garden with these simple and helpful tips for beginners passionate about gardening.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1135),
                            State = 0,
                            Title = "Gardening for Beginners",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 12,
                            Content = "Stay up-to-date with the latest tech gadgets that are both innovative and worth exploring in 2024.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1137),
                            State = 0,
                            Title = "Tech Gadgets Worth Exploring",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 13,
                            Content = "Boost your academic performance with these effective study habits that promote learning and retention.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1138),
                            State = 0,
                            Title = "Effective Study Habits",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 14,
                            Content = "Unleash your inner orator with tips and techniques to master the art of public speaking.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1140),
                            State = 0,
                            Title = "Art of Public Speaking",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 15,
                            Content = "Embrace a minimalist lifestyle with practical tips on decluttering and simplifying your life.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1142),
                            State = 0,
                            Title = "Minimalist Living Lifestyle",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 16,
                            Content = "Satisfy your cravings with nutritious and delicious healthy snack ideas for any time of the day.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1143),
                            State = 0,
                            Title = "Healthy Snack Ideas",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 17,
                            Content = "Embark on a language-learning journey with effective strategies and resources for beginners.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1145),
                            State = 0,
                            Title = "Learning a New Language",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 18,
                            Content = "Discover affordable fitness gear that will enhance your workouts without breaking the bank.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1147),
                            State = 0,
                            Title = "Budget-Friendly Fitness Gear",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 19,
                            Content = "Boost your productivity with these must-have apps designed for busy professionals.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1148),
                            State = 0,
                            Title = "Productivity Apps for Professionals",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 20,
                            Content = "Capture the beauty of nature with essential tips and techniques for stunning nature photography.",
                            DateTime = new DateTime(2024, 1, 17, 10, 58, 50, 72, DateTimeKind.Local).AddTicks(1150),
                            State = 0,
                            Title = "Nature Photography Essentials",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.PostTag", b =>
                {
                    b.Property<int>("PostID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostID", "TagID")
                        .HasName("PostTag_PK");

                    b.HasIndex("TagID");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            TagID = 1
                        },
                        new
                        {
                            PostID = 1,
                            TagID = 4
                        },
                        new
                        {
                            PostID = 2,
                            TagID = 2
                        },
                        new
                        {
                            PostID = 2,
                            TagID = 3
                        },
                        new
                        {
                            PostID = 3,
                            TagID = 5
                        },
                        new
                        {
                            PostID = 3,
                            TagID = 4
                        },
                        new
                        {
                            PostID = 4,
                            TagID = 8
                        },
                        new
                        {
                            PostID = 4,
                            TagID = 6
                        },
                        new
                        {
                            PostID = 5,
                            TagID = 7
                        },
                        new
                        {
                            PostID = 5,
                            TagID = 3
                        },
                        new
                        {
                            PostID = 6,
                            TagID = 1
                        },
                        new
                        {
                            PostID = 6,
                            TagID = 2
                        },
                        new
                        {
                            PostID = 7,
                            TagID = 18
                        },
                        new
                        {
                            PostID = 7,
                            TagID = 16
                        },
                        new
                        {
                            PostID = 8,
                            TagID = 14
                        },
                        new
                        {
                            PostID = 8,
                            TagID = 10
                        },
                        new
                        {
                            PostID = 9,
                            TagID = 11
                        },
                        new
                        {
                            PostID = 9,
                            TagID = 7
                        },
                        new
                        {
                            PostID = 10,
                            TagID = 12
                        },
                        new
                        {
                            PostID = 10,
                            TagID = 2
                        },
                        new
                        {
                            PostID = 11,
                            TagID = 13
                        },
                        new
                        {
                            PostID = 11,
                            TagID = 11
                        },
                        new
                        {
                            PostID = 12,
                            TagID = 3
                        },
                        new
                        {
                            PostID = 12,
                            TagID = 12
                        },
                        new
                        {
                            PostID = 13,
                            TagID = 9
                        },
                        new
                        {
                            PostID = 13,
                            TagID = 13
                        },
                        new
                        {
                            PostID = 14,
                            TagID = 10
                        },
                        new
                        {
                            PostID = 14,
                            TagID = 14
                        },
                        new
                        {
                            PostID = 15,
                            TagID = 15
                        },
                        new
                        {
                            PostID = 15,
                            TagID = 3
                        },
                        new
                        {
                            PostID = 16,
                            TagID = 16
                        },
                        new
                        {
                            PostID = 16,
                            TagID = 4
                        },
                        new
                        {
                            PostID = 17,
                            TagID = 17
                        },
                        new
                        {
                            PostID = 17,
                            TagID = 7
                        },
                        new
                        {
                            PostID = 18,
                            TagID = 18
                        },
                        new
                        {
                            PostID = 18,
                            TagID = 8
                        },
                        new
                        {
                            PostID = 19,
                            TagID = 19
                        },
                        new
                        {
                            PostID = 19,
                            TagID = 4
                        },
                        new
                        {
                            PostID = 20,
                            TagID = 20
                        },
                        new
                        {
                            PostID = 20,
                            TagID = 9
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("role_pk");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mod"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("TagId")
                        .HasName("Tag_PK");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Fitness"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Travel"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Health"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Cooking"
                        },
                        new
                        {
                            TagId = 6,
                            Name = "Mindfulness"
                        },
                        new
                        {
                            TagId = 7,
                            Name = "DIY"
                        },
                        new
                        {
                            TagId = 8,
                            Name = "Finance"
                        },
                        new
                        {
                            TagId = 9,
                            Name = "Photography"
                        },
                        new
                        {
                            TagId = 10,
                            Name = "Communication"
                        },
                        new
                        {
                            TagId = 11,
                            Name = "Gardening"
                        },
                        new
                        {
                            TagId = 12,
                            Name = "Tech"
                        },
                        new
                        {
                            TagId = 13,
                            Name = "Study"
                        },
                        new
                        {
                            TagId = 14,
                            Name = "Public Speaking"
                        },
                        new
                        {
                            TagId = 15,
                            Name = "Minimalism"
                        },
                        new
                        {
                            TagId = 16,
                            Name = "Snacks"
                        },
                        new
                        {
                            TagId = 17,
                            Name = "Language Learning"
                        },
                        new
                        {
                            TagId = 18,
                            Name = "Fitness Gear"
                        },
                        new
                        {
                            TagId = 19,
                            Name = "Productivity"
                        },
                        new
                        {
                            TagId = 20,
                            Name = "Nature Photography"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrefEng")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Roleid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId")
                        .HasName("User_PK");

                    b.HasIndex("Roleid");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DisplayName = "John Doe",
                            Password = "password",
                            PrefEng = false,
                            Roleid = 1,
                            Username = "john.doe"
                        },
                        new
                        {
                            UserId = 2,
                            DisplayName = "Jane Smith",
                            Password = "password",
                            PrefEng = false,
                            Roleid = 1,
                            Username = "jane.smith"
                        },
                        new
                        {
                            UserId = 3,
                            DisplayName = "Bob Johnson",
                            Password = "password",
                            PrefEng = false,
                            Roleid = 1,
                            Username = "bob.johnson"
                        },
                        new
                        {
                            UserId = 4,
                            DisplayName = "Alice Brown",
                            Password = "password",
                            PrefEng = false,
                            Roleid = 1,
                            Username = "alice.brown"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Comment", b =>
                {
                    b.HasOne("WebApplication1.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Post", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("User_Post");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WebApplication1.Models.PostTag", b =>
                {
                    b.HasOne("WebApplication1.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PostTag_Post");

                    b.HasOne("WebApplication1.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PostTag_Tag");

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.HasOne("WebApplication1.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApplication1.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("WebApplication1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
